package main

import "testing"

const example = `.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............`

func TestPart1(t *testing.T) {
	result := part1(example)
	expected := 21
	if result != expected {
		t.Errorf("part1() = %d, expected %d", result, expected)
	}
}

func TestPart2(t *testing.T) {
	result := part2(example)
	expected := 40
	if result != expected {
		t.Errorf("part2() = %d, expected %d", result, expected)
	}
}
